---

- hosts: all
  become: true
  tasks: 

  - name: create zygfryd user
    tags: always
    user:
      name: zygfryd
      groups: root



  - name: add sudoers zygfryd
    copy:
      src: sudoer_zygfryd
      dest: /etc/sudoers.d/zygfryd
      owner: root
      group: root
      mode: 0440