---

- hosts: all
  become: true
  tasks: 

  - name: install update
    tags: always
    apt:
      upgrade: dist
      update_cache: yes

- hosts: zapychacz
  become: true
  tasks:
    
  - name: install apache, php and update
    apt:
      name: 
        -  apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
  
  - name: copy default html for site
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644


- hosts: dbserw
  become: true
  tasks:
      
  - name: install db
    apt:
      name: mariadb-server
      state: latest
  

- hosts: pliki
  become: true
  tasks:
  
  - name: install samba package
    package:
      name: samba
      state: latest

  