---

- hosts: all
  become: true
  tasks: 

  - name: install update
    apt:
      upgrade: dist
      update_cache: yes

- hosts: zapychacz
  become: true
  tasks:
    
  - name: install apache, php and update
    apt:
      name: 
        -  apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes


- hosts: dbserw
  become: true
  tasks:
      
  - name: install db
    apt:
      name: mariadb-server
      state: latest
  

- hosts: pliki
  become: true
  tasks:
  
  - name: install samba package
    package:
      name: samba
      state: latest